# Generated by Django 5.0.6 on 2024-05-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('humidity', models.FloatField()),
                ('temperatureC', models.FloatField()),
                ('temperatureF', models.FloatField()),
                ('heatIndexC', models.FloatField()),
                ('heatIndexF', models.FloatField()),
                ('distanceCm', models.FloatField()),
                ('distanceInch', models.FloatField()),
            ],
        ),
    ]
