# Generated by Django 5.0.6 on 2024-05-31 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='heatIndexC',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='heatIndexF',
        ),
    ]
