# Generated by Django 5.0.6 on 2024-05-31 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_remove_sensordata_heatindexc_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SensorData',
        ),
    ]
